site_name: Tech Notes by Kolkhis
repo_url: https://github.com/kolkhis/tech-notes
theme:
  name: material
  palette:
    scheme: slate
  features:
    # - navigation.sections
    # - navigation.expand
    - navigation.top
    # - navigation.tabs
    - navigation.footer
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select

plugins:
  - search

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md

  - Linux:
    - linux/RAID.md
    - linux/ansi_control_sequences.md
    - linux/archives.md
    - linux/aws_lambda.md
    - linux/background_processes.md
    - linux/build_from_source.md
    - linux/command_cheatsheet_sysadmin.md
    - linux/customizing_terminal.md
    - linux/disk_types.md
    - linux/exercises.md
    - linux/filesystem-structure.md
    - linux/index.md
    - linux/jailing_users.md
    - linux/job_control.md
    - linux/kernel_panic.md
    - linux/lfoundation_lfs.md
    - linux/logical_volume_management.md
    - linux/manually_adding_user_accounts.md
    - linux/misc.md
    - linux/named_pipes.md
    - linux/network_commands.md
    - linux/nfs.md
    - linux/optiplex_ubuntu_server_install.md
    - linux/package_management.md
    - linux/permissions.md
    - linux/rhcsa-study-points.md
    - linux/samba.md
    - linux/selinux.md
    - linux/special_files.md
    - linux/strftime_datetime_formatting.md
    - linux/subshells_subprocesses.md
    - linux/system_files.md
    - linux/system_information_cmds.md
    - linux/system_logs.md
    - linux/topics_todo.md
    - linux/user_management.md
    - Bash:
      - linux/bash/ansi-c-quoting.md
      - linux/bash/arrays.md
      - linux/bash/bash_cheatsheet.md
      - linux/bash/cli_arguments.md
      - linux/bash/command_grouping.md
      - linux/bash/conditionals_in_bash.md
      - linux/bash/disk_commands.md
      - linux/bash/error_handling.md
      - linux/bash/loops.md
      - linux/bash/parameter_expansion.md
      - linux/bash/pattern_matching.md
      - linux/bash/process_substitution.md
      - linux/bash/programmable_bash_completion.md
      - linux/bash/redirection.md
      - linux/bash/switch_case.md
      - linux/bash/variables.md
      - linux/bash/version-checking.md
    - Ansible:
      - linux/ansible/ansible-doc.md
      - linux/ansible/ansible.md
      - linux/ansible/collections_in_ansible.md
      - linux/ansible/conditionals_in_ansible.md
      - linux/ansible/config.md
      - linux/ansible/inventory_files.md
      - linux/ansible/misc_ansible.md
      - linux/ansible/roles_in_ansible.md
      - linux/ansible/setting_up_ansible.md
      - linux/ansible/templates.md
      - linux/ansible/variables.md
    - Tools:
      - linux/tools/umask.md
      - linux/tools/aide.md
      - linux/tools/awk.md
      - linux/tools/bc.md
      - linux/tools/certtool.md
      - linux/tools/chmod_octal.md
      - linux/tools/cli_password_managers.md
      - linux/tools/cron.md
      - linux/tools/dd.md
      - linux/tools/du.md
      - linux/tools/ed.md
      - linux/tools/entr.md
      - linux/tools/fail2ban.md
      - linux/tools/find.md
      - linux/tools/fio.md
      - linux/tools/firewalld.md
      - linux/tools/fzf.md
      - linux/tools/getent.md
      - linux/tools/gpg.md
      - linux/tools/grep.md
      - linux/tools/heredocs.md
      - linux/tools/info.md
      - linux/tools/inotify-tools.md
      - linux/tools/inxi.md
      - linux/tools/iperf3.md
      - linux/tools/jq.md
      - linux/tools/kafka.md
      - linux/tools/kill.md
      - linux/tools/logger.md
      - linux/tools/logrotate.md
      - linux/tools/lsof.md
      - linux/tools/mount.md
      - linux/tools/nmap.md
      - linux/tools/passwd.md
      - linux/tools/printf.md
      - linux/tools/rbash.md
      - linux/tools/read.md
      - linux/tools/rsync_usage.md
      - linux/tools/screen.md
      - linux/tools/sed.md
      - linux/tools/set_shopt_shell_options.md
      - linux/tools/shopt.md
      - linux/tools/strace.md
      - linux/tools/sysctl.md
      - linux/tools/systemd.md
      - linux/tools/tar.md
      - linux/tools/top.md
      - linux/tools/trap_builtin.md
      - linux/tools/vmstat.md
      - linux/tools/wget.md
      - linux/tools/yq.md
    - Redhat:
      - linux/redhat/rhcsa-tasks.md
    - Monitoring:
      - linux/monitoring/monitoring_tools.md
      - linux/monitoring/prometheus_service_discovery.md
    - Tmux:
      - linux/tmux/copy_mode.md
      - linux/tmux/formats.md
      - linux/tmux/menus.md
      - linux/tmux/moving_panes.md
      - linux/tmux/overview_tmux.md
      - linux/tmux/scripting_notes.md
      - linux/tmux/styles_colors.md
      - linux/tmux/tmux_commands_arguments.md
      - linux/tmux/verbose_tmux_commands_arguments.md
    - Fundamentals:
      - linux/fundamentals/linux_structure.md
      - linux/fundamentals/system_commands.md
      - linux/fundamentals/user_and_group_management.md
    - I3wm:
      - linux/i3wm/getting_started.md
      - linux/i3wm/i3status.md
      - linux/i3wm/keybindings.md
      - linux/i3wm/sample_status_config.md
      - linux/i3wm/status.md

  - SSH:
    - ssh/config.md
    - ssh/hardening_ssh.md
    - ssh/monitoring_ssh_logs.md
    - ssh/ssh-copy-id.md
    - ssh/ssh-import-id.md
    - ssh/ssh-keygen.md
    - ssh/ssh-keyscan.md
    - ssh/sshd_management.md

  - Perl:
    - perl/arrays.md
    - perl/basics.md
    - perl/cheatsheet-regex.md
    - perl/cli-args.md
    - perl/docstrings.md
    - perl/file_operations.md
    - perl/loops.md
    - perl/operators.md
    - perl/regex.md
    - perl/variables.md

  - Golang:
    - golang/arrays.md
    - golang/builtin_functions.md
    - golang/byte_array_strings.md
    - golang/concurrency_in_go.md
    - golang/example_channel_goroutine.md
    - golang/files.md
    - golang/functions.md
    - golang/generics.md
    - golang/golang_ebnf.md
    - golang/interfaces.md
    - golang/iota.md
    - golang/json.md
    - golang/logging.md
    - golang/maps_associative_arrays.md
    - golang/method_signatures.md
    - golang/misc.md
    - golang/mod_tidy.md
    - golang/modules_and_packages.md
    - golang/pointers.md
    - golang/project_structure.md
    - golang/reading_user_input.md
    - golang/slices.md
    - golang/starting_a_new_project.md
    - golang/testing_in_go.md
    - golang/types_and_variables.md
    - golang/uninstalling_go.md

  - C:
    - c/basics.md
    - c/memory_management.md
    - c/pointers.md
    - c/primary_data_types.md
    - c/static_variables.md

  - Kubernetes:
    - kubernetes/deployments.md
    - kubernetes/install-k8s.md
    - kubernetes/kubectl.md
    - kubernetes/kubernetes.md
    - kubernetes/list_of_tools.md
    - kubernetes/manually_signing_usr_csr_crt.md
    - kubernetes/misc.md
    - kubernetes/security_in_k8s.md
    - kubernetes/tools-kubectl-kubeadm.md

  - Hashicorp:
    - hashicorp/hashicorp-vault.md
    - Terraform:
      - hashicorp/terraform/proxmox-terraform.md
      - hashicorp/terraform/ansible_and_terraform.md
      - hashicorp/terraform/deploy_docker_containers_terraform.md
      - hashicorp/terraform/install_terraform.md
      - hashicorp/terraform/tf-project-structure.md

  - AWS:
    - aws/ccp-notes.md
    - aws/containers.md
    - aws/ec2.md
    - aws/global_infrastructure.md
    - aws/lambda.md
    - aws/loosely_coupled_architecture.md
    - aws/misc_aws_notes.md
    - aws/pricing_ec2.md
    - aws/s3.md

  - Networking:
    - networking/network_primer.md
    - networking/network_storage.md
    - networking/network_tools.md
    - networking/notes_week13.md
    - networking/packet_types.md
    - networking/subnetting.md

  - SQL:
    - sql/basics.md
    - sql/exploring_a_database.md

  - Hax:
    - hax/hide_website_wall.md
    - hax/misc.md
    - hax/nopslide.md
    - hax/resources.md
    - hax/sql_injections.md
    - Flipper:
      - hax/flipper/basics.md
      - hax/flipper/cli_flipper.md
      - hax/flipper/wifi_devboard.md
    - Scripting:
      - hax/flipper/scripting/basics.md
      - hax/flipper/scripting/os_scripting.md
      - hax/flipper/scripting/script_format.md
    - Ciphers:
      - hax/ciphers/challenge_ciphers.md
      - hax/ciphers/encryption_and_cipher_types.md
      - hax/ciphers/misc_notes.md
      - hax/ciphers/tools.md
      - hax/ciphers/utf-8.md

  - Misc:
    - misc/atomic_operations.md
    - misc/big-o.md
    - misc/binary_octal_hexadecimal.md
    - misc/cicd_pipeline.md
    - misc/connect_twitch_chat_via_irc.md
    - misc/cool_characters.md
    - misc/data_structures.md
    - misc/exporter-default-ports.md
    - misc/interview-tips.md
    - misc/k8s_in_enterprise.md
    - misc/markdown_cheatsheet.md
    - misc/mkdocs.md
    - misc/non-printable-chars.md
    - misc/radio_waves_rfid_types.md
    - misc/sre_tools.md
    - misc/w3m.md
    - misc/xterm.md
  - Podman:
    - podman/dockerfile-builds-best-practices.md
    - podman/podman.md
  - Homelab:
    - homelab/bastion.md
    - homelab/homelab_initial_setup.md
    - homelab/storage-rebuild.md
    - homelab/troubleshooting.md
    - homelab/hardware-raid-controller.md
    - homelab/project_k8s_haproxy_keepalived.md
    - homelab/cloud-init.md
  - WEB:
    - web/domain-configuration.md
    - Javascript:
      - web/javascript/thirty_days.md
    - Basics:
      - web/javascript/basics/basics.md
      - web/javascript/basics/closures.md
      - web/javascript/basics/dynamic_strings.md
      - web/javascript/basics/hoisting.md
      - web/javascript/basics/node_vs_js.md
      - web/javascript/basics/starting_a_project.md
      - web/javascript/basics/template_literals.md
    - Html css:
      - web/html_css/basics.md
      - web/html_css/flexbox.md
  - Chaos engineering:
    - chaos-engineering/gremlin.md
  - Windows:
    - windows/ad_groups.md
    - windows/batch-scripts.md
    - windows/cygwin.md
    - windows/powershell_profile.md
    - windows/windows_format_drive.md
    - windows/wsl2.md
  - Git:
    - git/actions.md
    - git/commit-metadata.md
    - git/basic_contribution_workflow.md
    - git/branches.md
    - git/checkout_operations.md
    - git/commands.md
    - git/commit_message_convention.md
    - git/creating_notes_repo.md
    - git/fetch_one_file.md
    - git/gh.md
    - git/github_user_keys.md
    - git/gpg_for_git.md
    - git/issue-templates.md
    - git/misc.md
    - git/modify_author.md
    - git/remove_file_from_history.md
    - git/rollback_commit.md
    - git/special_files.md
    - git/squashing.md
    - git/ssh_for_git.md
    - git/stash.md
    - git/submodules.md
    - git/sync_local_repo.md
    - git/tags.md
  - Vi/Vim:
    - vim/argument_list.md
    - vim/buffer_list.md
    - vim/build_from_source.md
    - vim/color_column.md
    - vim/digraphs.md
    - vim/encrypt.md
    - vim/ex_commands.md
    - vim/formatting.md
    - vim/keybind_cheatsheet.md
    - vim/line_manipulation.md
    - vim/macros.md
    - vim/misc_vim_notes.md
    - vim/navigating_buffers.md
    - vim/neovim_conf_2023.md
    - vim/no_plugins.md
    - vim/regex_in_vim.md
    - vim/substitute.md
    - vim/tabs.md
    - vim/vim_help.md
    - vim/windows.md
    - vim/your_problem_with_vim_is_that_you_dont_grok_vi.md
    - Netrw:
      - vim/netrw/commands_functions.md
      - vim/netrw/filetree.md
      - vim/netrw/functions.md
      - vim/netrw/keybindings.md
      - vim/netrw/netrw.md
      - vim/netrw/remote_files.md
    - Nvim:
      - vim/nvim/autocmds.md
      - vim/nvim/config_directory_structure.md
      - vim/nvim/external_processes.md
      - vim/nvim/lsp.md
      - vim/nvim/lua_api.md
      - vim/nvim/terminal_mode.md
      - vim/nvim/vim_variables.md
    - Lua:
      - vim/lua/nvim_lua_stdlib.md
      - vim/lua/patterns.md
      - vim/lua/regex_in_lua.md
      - vim/lua/sorting_tables.md
    - Vimscript:
      - vim/vimscript/basics.md
      - vim/vimscript/functions.md

  - Python:
    - python/fstrings.md
    - python/logging.md
    - python/misc.md
    - python/pdb.md
    - python/pyproject.toml.md
    - python/requirements.txt.md
    - python/special_fn_parameters.md

  - Security:
    - security/STIG.md
    - security/acronyms.md
    - security/controls.md
    - security/misc.md
    - security/shell-injection.md
