#!/bin/bash

declare -a DEPS=(
    "sort=8.1"
    "bash=3.2"
    "ld=2.13.1"
    "bison=2.7"
    "diff=2.8.1"
    "find=4.2.31"
    "gawk=4.0.1"
    "gcc=5.4"
    "g++=5.4"
    "grep=2.5.1a"
    "gzip=1.3.12"
    "m4=1.4.10"
    "make=4.0"
    "patch=2.5.4"
    "perl=5.8.8"
    "python3=3.4"
    "sed=4.1.5"
    "tar=1.22"
    "texi2any=5."
    "xz=5.0.0"
)

sudo apt-get install -y "${DEPS[@]}"



