# NOT a ROT13 cipher. Requires frequency analysis to solve. The solution is the flag for this challenge.

ciphertxt='CGZNL YJBEN QYDLQ ZQSUQ NZCYD SNQVU BFGBK GQUQZ QSUQN UZCYD SNJDS UDCXJ ZCYDS NZQSU QNUZB WSBNZ QSUQN UDCXJ CUBGS BXJDS UCTYV SUJQG WTBUJ KCWSV LFGBK GSGZN LYJCB GJSZD GCHMS UCJCU QJLYS BXUMA UJCJM JCBGZ CYDSN CGKDC ZDSQZ DVSJJ SNCGJ DSYVQ CGJSO JCUNS YVQZS WALQV SJJSN UBTSX COSWG MTASN BXYBU CJCBG UWBKG JDSQV YDQAS JXBNS OQTYV SKCJD QUDCX JBXQK BMVWA SNSYV QZSWA LWAKB MVWAS ZBTSS QGWUB BGJDS TSJDB WCUGQ TSWQX JSNRM VCMUZ QSUQN KDBMU SWCJJ BZBTT MGCZQ JSKCJ DDCUE SGSNQ VUJDS SGZNL YJCBG UJSYY SNXBN TSWAL QZQSU QNZCY DSNCU BXJSG CGZBN YBNQJ SWQUY QNJBX TBNSZ BTYVS OUZDS TSUUM ZDQUJ DSICE SGNSZ CYDSN QGWUJ CVVDQ UTBWS NGQYY VCZQJ CBGCG JDSNB JULUJ STQUK CJDQV VUCGE VSQVY DQASJ UMAUJ CJMJC BGZCY DSNUJ DSZQS UQNZC YDSNC USQUC VLANB FSGQG WCGYN QZJCZ SBXXS NUSUU SGJCQ VVLGB ZBTTM GCZQJ CBGUS ZMNCJ LUDQF SUYSQ NSYNB WMZSW TBUJB XDCUF GBKGK BNFAS JKSSG QGWDC USQNV LYVQL UKSNS TQCGV LZBTS WCSUQ GWDCU JBNCS UESGN SUDSN QCUSW JBJDS YSQFB XUBYD CUJCZ QJCBG QGWQN JCUJN LALJD SSGWB XJDSU COJSS GJDZS GJMNL GSOJD SKNBJ STQCG VLJNQ ESWCS UMGJC VQABM JCGZV MWCGE DQTVS JFCGE VSQNQ GWTQZ ASJDZ BGUCW SNSWU BTSBX JDSXC GSUJS OQTYV SUCGJ DSSGE VCUDV QGEMQ ESCGD CUVQU JYDQU SDSKN BJSJN QECZB TSWCS UQVUB FGBKG QUNBT QGZSU QGWZB VVQAB NQJSW KCJDB JDSNY VQLKN CEDJU TQGLB XDCUY VQLUK SNSYM AVCUD SWCGS WCJCB GUBXI QNLCG EHMQV CJLQG WQZZM NQZLW MNCGE DCUVC XSJCT SQGWC GJKBB XDCUX BNTSN JDSQJ NCZQV ZBVVS QEMSU YMAVC UDSWJ DSXCN UJXBV CBQZB VVSZJ SWSWC JCBGB XDCUW NQTQJ CZKBN FUJDQ JCGZV MWSWQ VVAMJ JKBBX JDSYV QLUGB KNSZB EGCUS WQUUD QFSUY SQNSU'

# ciphertxt='CGZNL YJBEN QYDLQ ZQSUQ NZCYD SNQVU BFGBK GQUQZ QSUQN UZCYD SNJDS UDCXJ ZCYDS NZQSU QNUZB WSBNZ'

# N LETTER
ENG_FREQ=(
"E"
"T"
"A"
"O"
"I"
# "N"
# "S"
# "R"
# "H"
# "L"
# "D"
# "C"
# "U"
# "M"
# "F"
# "P"
# "G"
# "W"
# "Y"
# "B"
# "V"
# "K"
# "X"
# "J"
# "Q"
# "Z"
)

# CIPHER_FREQ=($(echo "$ciphertxt" | tr -d ' ' | fold -w1 | sort | uniq -c | sort -rn | perl -pe 's/^\s*\d+\s+(.)/$1/'))
declare -a CIPHER_FREQ
read -r -d '' -a CIPHER_FREQ < <(
    echo "$ciphertxt" | tr -d ' ' | fold -w1 | sort | uniq -c | sort -rn | perl -pe 's/^\s*\d+\s+(.)/$1/' | head -n 5
)

declare newtxt="$ciphertxt"
declare -i i=0
for (( i=0; i<"${#CIPHER_FREQ[@]}"; i++)); do

    cur_letter="${CIPHER_FREQ[$i]}"
    new_letter="${ENG_FREQ[$i]}"
    printf "Replacing letter %s with %s\n" "$cur_letter" "$new_letter"

    newtxt="$(perl -pe "s/$cur_letter/$new_letter/g" <<< "$newtxt")"
    printf "New text:\n\n%s\n" "$newtxt"
    sleep 0.5
done

printf "New text:\n %s\n" "$newtxt"



