#!/bin/bash

declare -a EXCLUDE_DIRS=(
    "./docs"
    "./venv"
    "./.git"
    "./.github"
    "./."
    "./ai"
    "./ai/chatgpt_prompts"
    "./proxmox"
    "./skilstak"
    "./pi"
    "./nix"
    "./api"
    "./killercoda"
    "./android"
    "./hax/htb"
    "./hax/thm"
    "./linux/mint"
    "./linux/lfcs"
    "./linux/labs"
    "./linux/labs/linux"
    "./linux/labs/hashicorp"
    "./aws/cloud_quest"
    ""
)

declare -a EXCLUDE_KEYWORDS=(
    "skilstak"
    "beginner_boost"
    "chatgpt_prompts"
)

add-newlines-before-lists(){
    shopt -s globstar
    if ! type perl >/dev/null 2>&1; then
        printf >&2 "[ERROR]: Perl not found on the system.\n"
        return 1
    fi
    if [[ -f ./action-scripts/newlineadd.pl ]]; then
        /usr/bin/perl ./action-scripts/newlineadd.pl
    else
        perl -pi -e '
            my $newline_pattern=qr/^(?:\s*[*-]|\s*\d{1,}\.|[|])/;
            print "\n" if ((m/$newline_pattern/) && $prev !~ (m/$newline_pattern|^\n/));
            $prev = $_' ./docs/**/*.md
    fi
}


copy-to-docs() {
    local -a FILES
    read -r -d '' -a FILES < <(
        find . -maxdepth 1 -mindepth 1 #-type d
    )

    if ! [[ -d ./docs ]]; then
        mkdir docs || { printf "Failed to create docs directory!\n"; }
    fi

    for FILE in "${FILES[@]}"; do
        if [[ "${EXCLUDE_DIRS[*]}" =~ [[:space:]]${FILE}[[:space:]] ||
            "${EXCLUDE_KEYWORDS[*]}" =~ ${FILE} ]]; then
            printf "Found exlusion directory: %s\n" "$FILE" && continue
        fi
        printf "DEBUG: File: %s \n" "$FILE"
        [[ -f $FILE ]] && printf " %s is a regular file.\n" "$FILE"

        if [[ ! -h $FILE ]]; then
            # Recursive copying copies symlinks (bad)
            # cp -r "$FILE" ./docs
            rsync -a --no-links "$FILE" ./docs
        fi
    done
}

copy-to-docs
add-newlines-before-lists

