#!/bin/bash

read -r -a ciphers < ./cipher_list.txt
str=$(cat ./salted.txt)
printf "Cipher list: %s\n" "${ciphers[@]}"

# for c in ${#ciphers}; do
while read -r c; do
    # phrase=$(openssl enc -a "$c")
    printf "Cipher Being Used: %s\n" "$c"
    # printf "Being Decoded: \n%s\n" "$phrase"
    echo "$str" | openssl enc -a -d -"$c" -pbkdf2 -pass pass:P4ssw0rd
done <cipher_list.txt

