#!/bin/bash
# !! <- shortcut for :.! 
# :.!termcolors

red=$'\e[31m'
green=$'\e[32m'
yellow=$'\e[33m'
reset=$'\e[0m'

output() {
    # declare -i max=$1  # This is POSIX-compliant
    # local -i max="$1"
    # local sec=$2    # This is bash-only
    # local color=$3
    # local string=$4
    local -i max="$1"
    local sec=$2 color=$3 string=$4
    for ((count=1; count <= max; count++)); do
        printf "%s %s %s\n" "$color$count" "$string" "$reset"
        sleep "$sec"
    done
}

verse() {
    output 12 0.3 "$green" "badgers!"
    output 2 0.6 "$yellow" "mushrooms!"
}

chorus() {
    output 1 1 "$red" "Ahh snake, ahh snake, ahh snake!!\n"
}

for _ in {1..3}; do verse; done  # Bash-only trick
chorus
verse




# count=0
# while [[ count -le 2 ]]; do
#     printf "%s mushrooms!\n" "$count"
#     sleep 0.6
#     count=$(( count + 1 ))
# done

